### ISSUE TITLE
Animated blocks have no animation (with Sodium `v0.6.0`)

### ISSUE THREAD

**Issue by anoomolu** [IMB11/Fog#23] opened 2024-08-24 11:53 UTC
## Workaround:

- Disable the "Animate Only Visible Textures" in the "Performance" tab of the sodium settings screen.

![java_Pe4GJju2hq](https://github.com/user-attachments/assets/c645c4b9-6c32-4016-babe-f747b6b6892c)

---

When Sodium's "Animate Only Visible Textures" setting is enabled, which is the case by default, adding Fog causes the animated texture of fire to become static. Disabling the former setting is a workaround for the issue, but I'm not sure why Fog would cause such an issue to begin with.

Using the following modlist:
![image](https://github.com/user-attachments/assets/cf4099a6-6e28-48de-98f9-09ac8c1bd659)

**Comment by zed1ker** [comment] 2024-08-25 14:38
same problem

**Comment by DmanMC** [comment] 2024-08-29 12:08
its any block texture animation, liquids arent affected
[Screencast_20240829_080418.webm](https://github.com/user-attachments/assets/903b0327-a351-4372-9302-44eb3fe8f013)

**Comment by IMB11** [comment] 2024-08-30 18:26
This is insanely weird, fixing now.

**Comment by IMB11** [comment] 2024-08-30 18:52
I cant seem to reproduce this on 1.21 with Sodium 0.6, I will try with the older versions.

https://github.com/user-attachments/assets/2038d1d1-31b3-4dd2-a3f0-aad62bd283cd

**Comment by zed1ker** [comment] 2024-08-30 20:25
I had it on 1.21, perhaps this is due to a special setting

**Comment by zed1ker** [comment] 2024-08-30 20:34
the person who started the issue has several mods, I have a little more of them, but the error occurs only if there is a Fog mod

https://github.com/user-attachments/assets/29a139aa-eee1-4c68-9f48-f819fa94171c

**Comment by IMB11** [comment] 2024-08-31 09:36
Im not sure, can you remove your mods one by one until the issue no longer occurs? (Obviously keeping Fog and MRU installed.)

**Comment by IMB11** [comment] 2024-08-31 09:41
For now, simply just disable the "Animate only Visible Textures" option as a workaround.

**Comment by zed1ker** [comment] 2024-08-31 09:49
I created a completely new build and added a couple of mods that everyone usually uses.

I'm going to delete 1 mod at a time and look for incompatibilities

https://github.com/user-attachments/assets/9a0dd829-2879-4e04-a278-29195c3c59be

**Comment by anoomolu** [comment] 2024-08-31 09:53
Will be home in an hour or so, can check then if the problematic mod isn't found by then.

**Comment by zed1ker** [comment] 2024-08-31 10:01
4 mods are installed mru, fog, fabric api and sodium 

the video is slightly accelerated to take up less space

https://github.com/user-attachments/assets/2bc68b98-e3d2-4259-b0be-d9568bed5a92

**Comment by IMB11** [comment] 2024-08-31 10:08
Does this happen on 1.21.1 as well?

**Comment by IMB11** [comment] 2024-08-31 10:08
It could be an issue with your GPU, you might have to report this to sodium, I have not a single clue why Fog causes this issue considering we're only modifying the fog manager.

**Comment by zed1ker** [comment] 2024-08-31 10:27
it 1.21
maybe something is wrong with my gpu and apparently not only with mine

**Comment by God-Dnds** [comment] 2024-09-01 05:56
Same issue here, running only Fog and its required mods. (Side note it gave me an error [fabric-renderer-indigo] and wouldn't launch at all so I through in indium and sodium)
Fabric 1.21

**Comment by God-Dnds** [comment] 2024-09-02 03:39
Addition to previous note all particles seem to disappear as well so it must be breaking something in indigo renderer.

**Comment by vico93** [comment] 2024-09-02 16:44
Having the same issue on 1.21.1 and Sodium 0.6.0.

**Comment by Steveplays28** [comment] 2024-09-02 19:43
@God-Dnds could you reproduce that issue with Indigo and upload your `latest.log`?

**Comment by God-Dnds** [comment] 2024-09-02 20:16
I would but I'm not able to reproduce it so it may have been something else but as far as I know none of the other mods I am using are using Indigo. I was noticing the issue like 2ish hours into playing and I am having to clear logs constantly since for one of the data packs I am using is spitting out literal Gigabytes of log files. I will test without any of that for a few hours and report back

**Comment by MiraculixxT** [comment] 2024-09-05 16:28
I also opened an issue on the Sodium GitHub page 2 weeks ago, the issue started with Sodium 0.6 beta. Also uploaded a full log and crashlog for hardware.
Issue: https://github.com/CaffeineMC/sodium-fabric/issues/2722

**Comment by IMB11** [comment] 2024-09-09 22:42
This will be fixed in the next version of sodium: https://github.com/CaffeineMC/sodium-fabric/issues/2722

**Closed by IMB11** 2024-09-09 22:42 UTC
Labels: bug, compat
