### ISSUE TITLE
Fog doesent work with the Better Clouds mod

### ISSUE THREAD

**Issue by BeagleNF404** [IMB11/Fog#50] opened 2024-10-26 10:35 UTC
It renders realy weirdly any idea why?

**Comment by BeagleNF404** [comment] 2024-10-26 10:36
![2024-10-26_12 34 36](https://github.com/user-attachments/assets/623ad329-dc9a-495a-bd97-234f3cdcb4e4)
![2024-10-26_12 34 47](https://github.com/user-attachments/assets/9bd5b6a3-5274-4705-9782-7694b6454914)

**Comment by Steveplays28** [comment] 2024-10-26 10:46
Duplicate of #17, see that issue for why this happens.

**Closed by Steveplays28** 2024-10-26 10:46 UTC
